### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by brunocordeiro180** [combateafraude/document-detector-ionic#3]
Não estou conseguindo utilizar o sdk com o ionic, apresenta o erro como mostrado na imagem. Obs: estou utilizando o ionic com o cordova.

![WhatsApp Image 2022-04-28 at 16 56 41](https://user-images.githubusercontent.com/19695449/165836435-474c54cf-079d-4068-9700-7caebbb83ca8.jpeg)

**Comment by dbseitenfus** [comment]
Olá, @brunocordeiro180 
Atualmente estamos oferencendo suporte somente a projetos com [Capacitor](https://capacitorjs.com/).
