### ISSUE TITLE
Aplicativo para de funcionar ao utilizar DocumentDetector

### ISSUE THREAD

**Issue by brunocordeiro180** [combateafraude/document-detector-ionic#4]
Em um projeto utilizando capacitor foi adicionado o pacote do documentDetector e o código de exemplo do README do projeto. Porém ao acionar a função contendo o código de exemplo o aplicativo fecha e para de funcionar. Rodei o aplicativo em modo debug para ver se algum erro seria mostrado no console.log porém nada foi mostrado. Alguma ideia de qual pode ser o erro? Devo incluir algum outro pacote do npm?

**Comment by dbseitenfus** [comment]
Olá, @brunocordeiro180. Você está informando um [mobileToken](https://docs.combateafraude.com/docs/mobile/introduction/mobile-token/) válido?

**Comment by brunocordeiro180** [comment]
@dbseitenfus sim no caso o mobileToken que estou usando é o mesmo que utilizo para mandar requisições na api da caf, como no exemplo: https://api.combateafraude.com/execute/:reportId?token=:mobileToken

**Comment by dbseitenfus** [comment]
São tokens de autenticação diferentes. A geração mobile token está na documentação dos SDKs da Combate à Fraude https://docs.combateafraude.com/docs/mobile/introduction/mobile-token/

Caso necessite de auxílio, por favor, entrar em contato com o time de Implementação. 
Estou fechando a _issue_, caso necessário, pode reabri-la.
